### ISSUE TITLE
Exclude flag not respected

### ISSUE THREAD

**Issue by spiderpug** [AtomLinter/linter-rubocop#356]
I found issue #43 which was fixed in #72 , however the fix was not carried over with the rewrite done in version 1.0.0.

# Usecase

Rubocop should not autoformat 'db/schema.rb':

```yml
# rubocop.yml
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/schema.rb'
```

# Expectation
Editing `schema.rb` should not store file content modified by Rubocop.

# Actual
File is formatted using Rubocop.

# Analysis

In v.1.0 the `stdin` option is no longer used. See the comparison between `index.coffee` and `index.js`: https://github.com/AtomLinter/linter-rubocop/compare/v0.5.3...v1.0.0
